-- Generated by po_setup.py render-access from config/project.yaml. Do not edit by hand.
-- Run by a HUMAN with sufficient rights, once in EACH agent-enabled database:
--   RICS_Dev, RICS_Test
-- Creates one role per agent. Idempotent.
SET NOCOUNT ON;

IF DATABASE_PRINCIPAL_ID(N'agent_product_owner') IS NULL CREATE ROLE [agent_product_owner];
IF DATABASE_PRINCIPAL_ID(N'agent_analyst') IS NULL CREATE ROLE [agent_analyst];
IF DATABASE_PRINCIPAL_ID(N'agent_technical_architect') IS NULL CREATE ROLE [agent_technical_architect];
IF DATABASE_PRINCIPAL_ID(N'agent_developer') IS NULL CREATE ROLE [agent_developer];
IF DATABASE_PRINCIPAL_ID(N'agent_tester') IS NULL CREATE ROLE [agent_tester];
IF DATABASE_PRINCIPAL_ID(N'agent_technical_writer') IS NULL CREATE ROLE [agent_technical_writer];
GO
