-- Generated by po_setup.py render-access from config/project.yaml. Do not edit by hand.
-- HUMAN-RUN. Creates one login/user per agent that needs database access and adds it to its role.
-- Run in SQLCMD mode once in each database (RICS_Dev, RICS_Test), AFTER 01_create_roles.sql.
-- Only agents with access to the current database get a user there (see ACCESS_MATRIX.md).
--
-- Secrets never go in the repo. Pass passwords at run time from your secret store, e.g.
--   sqlcmd -S localhost -d <database> -U sa -i 02_create_agent_users.sql -v Platform=SQLSERVER Pwd_analyst="..." Pwd_developer="..." Pwd_product_owner="..." Pwd_technical_architect="..." Pwd_tester="..."
-- Platform = SQLSERVER: server logins + database users (local). AZURESQL: contained users.
-- Passwords must not contain a single quote.

:on error exit
SET NOCOUNT ON;
DECLARE @platform sysname = N'$(Platform)';
DECLARE @agents TABLE (agent sysname, login sysname, role sysname, pwd nvarchar(256), db sysname);
INSERT @agents VALUES
 (N'product_owner', N'rics_agent_product_owner', N'agent_product_owner', N'$(Pwd_product_owner)', N'RICS_Dev'),
 (N'product_owner', N'rics_agent_product_owner', N'agent_product_owner', N'$(Pwd_product_owner)', N'RICS_Test'),
 (N'analyst', N'rics_agent_analyst', N'agent_analyst', N'$(Pwd_analyst)', N'RICS_Dev'),
 (N'technical_architect', N'rics_agent_technical_architect', N'agent_technical_architect', N'$(Pwd_technical_architect)', N'RICS_Dev'),
 (N'developer', N'rics_agent_developer', N'agent_developer', N'$(Pwd_developer)', N'RICS_Dev'),
 (N'tester', N'rics_agent_tester', N'agent_tester', N'$(Pwd_tester)', N'RICS_Dev'),
 (N'tester', N'rics_agent_tester', N'agent_tester', N'$(Pwd_tester)', N'RICS_Test');

DECLARE @login sysname, @role sysname, @pwd nvarchar(256), @sql nvarchar(max);
DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT login, role, pwd FROM @agents WHERE db = DB_NAME();
OPEN c;
FETCH NEXT FROM c INTO @login, @role, @pwd;
WHILE @@FETCH_STATUS = 0
BEGIN
  IF @platform = N'SQLSERVER'
  BEGIN
    IF SUSER_ID(@login) IS NULL
    BEGIN
      SET @sql = N'CREATE LOGIN ' + QUOTENAME(@login) + N' WITH PASSWORD = ' + QUOTENAME(@pwd, '''')
               + N', DEFAULT_DATABASE = ' + QUOTENAME(DB_NAME()) + N', CHECK_POLICY = ON;';
      EXEC (@sql);
    END
    IF DATABASE_PRINCIPAL_ID(@login) IS NULL
    BEGIN
      SET @sql = N'CREATE USER ' + QUOTENAME(@login) + N' FOR LOGIN ' + QUOTENAME(@login) + N';';
      EXEC (@sql);
    END
  END
  ELSE IF @platform = N'AZURESQL'
  BEGIN
    IF DATABASE_PRINCIPAL_ID(@login) IS NULL
    BEGIN
      SET @sql = N'CREATE USER ' + QUOTENAME(@login) + N' WITH PASSWORD = ' + QUOTENAME(@pwd, '''') + N';';
      EXEC (@sql);
    END
  END
  ELSE THROW 50001, 'Platform must be SQLSERVER or AZURESQL', 1;

  IF ISNULL(IS_ROLEMEMBER(@role, @login), 0) = 0
  BEGIN
    SET @sql = N'ALTER ROLE ' + QUOTENAME(@role) + N' ADD MEMBER ' + QUOTENAME(@login) + N';';
    EXEC (@sql);
  END
  FETCH NEXT FROM c INTO @login, @role, @pwd;
END
CLOSE c; DEALLOCATE c;
GO
