-- Generated by po_setup.py render-access from config/project.yaml. Do not edit by hand.
-- Environment: dev  Database: RICS_Dev
-- Run by a HUMAN after 01_create_roles.sql. Review every line before running.
USE [RICS_Dev];
SET NOCOUNT ON;

-- product_owner: metadata_read
GRANT VIEW DEFINITION TO [agent_product_owner];

-- analyst: metadata_read
GRANT VIEW DEFINITION TO [agent_analyst];

-- technical_architect: metadata_read
GRANT VIEW DEFINITION TO [agent_technical_architect];

-- developer: build
GRANT VIEW DEFINITION TO [agent_developer];
ALTER ROLE [db_datareader] ADD MEMBER [agent_developer];
ALTER ROLE [db_datawriter] ADD MEMBER [agent_developer];
ALTER ROLE [db_ddladmin] ADD MEMBER [agent_developer];
GRANT EXECUTE TO [agent_developer];
GRANT SHOWPLAN TO [agent_developer];

-- tester: data_read
GRANT VIEW DEFINITION TO [agent_tester];
ALTER ROLE [db_datareader] ADD MEMBER [agent_tester];

-- technical_writer: none

GO
