-- Generated by po_setup.py render-access from config/project.yaml. Do not edit by hand.
-- Environment: test  Database: RICS_Test
-- Run by a HUMAN after 01_create_roles.sql. Review every line before running.
USE [RICS_Test];
SET NOCOUNT ON;

-- product_owner: metadata_read
GRANT VIEW DEFINITION TO [agent_product_owner];

-- analyst: none

-- technical_architect: none

-- developer: none

-- tester: test_execute
GRANT VIEW DEFINITION TO [agent_tester];
ALTER ROLE [db_datareader] ADD MEMBER [agent_tester];
ALTER ROLE [db_datawriter] ADD MEMBER [agent_tester];
ALTER ROLE [db_ddladmin] ADD MEMBER [agent_tester];
GRANT EXECUTE TO [agent_tester];

-- technical_writer: none

GO
