-- MIG-0002 (down): BASELINE, not reversible. A database goes back to before its baseline by restoring a backup.
-- Generated by import_baseline.py from phase1/ (the existing solution); do not edit by hand.
-- Run in SQLCMD mode with -v CommitHash=<git sha>, after MIG-0000 and MIG-0001. Safe to run twice.
:on error exit
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
IF etl.fn_MigrationIsApplied('MIG-0002') = 0
BEGIN
    PRINT 'MIG-0002 not applied; nothing to roll back.';
    SET NOEXEC ON;
END
GO
THROW 50013, 'MIG-0002 is the baseline of an existing solution and is not rolled back: restore a backup instead.', 1;
GO
SET NOEXEC OFF;
GO
